# Generated by Django 3.0.7 on 2020-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_makepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Enter your M-PESA mobile number'),
        ),
    ]
