# Generated by Django 3.0.7 on 2020-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201005_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
