# Generated by Django 3.0.7 on 2020-10-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_total',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
