# Generated by Django 3.0.7 on 2020-10-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_makepayment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order'),
        ),
    ]
